### ISSUE TITLE
about real-time

### ISSUE THREAD

**Issue by lijingle-coder** [sitzikbs/3DmFV-Net#3]
thinks for you work
I would like to know, the real-time network in what environment, how many frames per second can be achieved, thinks

**Comment by sitzikbs** [comment]
In the paper, we report the system and timing. 
We used a Titan Xp GPU and were able to achieve about 3ms per point cloud (for 1024 points and the 8x8x8 gaussian grid). 

So the frame rate really depends on how many points you sample per object and how many Gaussians you choose to use.

**Comment by MRshiyf** [comment]
i used a tesla T4 GPU and achieved about 100ms per point cloud (for 1024 points and the 8x8x8 gaussian grid), how does the diff happened？ GPU performence？cuda version？
my env is ubuntu14 + cuda10 + cudnn7 + T4 GPU + tensorflow1.13.1

**Comment by sitzikbs** [comment]
There may be several reasons for this. 
a. CPU bottlenecking (check to see if your CPU is overloading while your GPU is waiting for commands.
b. I used Python 2.7, TensorFlow 1.2.1, CUDA 8.0.61 and cuDNN 5105 on Ubuntu 16.04  with a Titan XP in my tests. 
c. if you increase the batch size, speed will almost definitely improve. 
d. Make sure you are timing just the inference.
