### ISSUE TITLE
run time issue

### ISSUE THREAD

**Issue by MRshiyf** [sitzikbs/3DmFV-Net#4]
i used a tesla T4 GPU and achieved about 100ms per point cloud (for 1024 points and the 8x8x8 gaussian grid), how does the diff happened？ GPU performence？cuda version？
my env is ubuntu14 + cuda10 + cudnn7 + T4 GPU + tensorflow1.13.1
and i found net structure is related to  batch_size, in order to evaluate time consume
i trained with batch size = 1

**Comment by sitzikbs** [comment]
Answered [here ](https://github.com/sitzikbs/3DmFV-Net/issues/3#issuecomment-497967025)
