### ISSUE TITLE
visualization.py in line 640  tf_util.pc_svd 

### ISSUE THREAD

**Issue by WillingDil** [sitzikbs/3DmFV-Net#6]
Thanks a lot for your work.
when I run the visulization.py file, there is an error about the  tf_util.pc_svd function, I have seen the tf_uitl.py file, but I don't find the pc_svd function,
appreciate your some advice at anytime

**Comment by sitzikbs** [comment]
This functionality is unsupported.
I removed it from the `visualization.py` file to prevent the error.

**Comment by WillingDil** [comment]
I know, Thank you for your time
